### ISSUE TITLE
Stlying on demo. FF21 osx. 

### ISSUE THREAD

**Issue by fionnbharra** [mtkopone/zelect#11]
The text box is breaking out of it's container. 

Firefox 21 - OSX.

![screen shot 2013-05-22 at 14 43 29](https://f.cloud.github.com/assets/860228/548510/a1416594-c2e5-11e2-99ea-077c9c0b08e1.png)

**Comment by mtkopone** [comment]
Fixed.
Was missing -moz prefix of box-sizing css...
