### ISSUE TITLE
Val of the original select doesn't get updated if value evaluates to false

### ISSUE THREAD

**Issue by joux3** [mtkopone/zelect#4]
Example: http://www.niksula.hut.fi/~ristela1/zelect_bug/
Fixed behaviour: http://www.niksula.hut.fi/~ristela1/zelect_bug/index_with_fix.html

**Comment by antris** [comment]
I've added tests for this. https://github.com/antris/zelect/commit/321a6230eb6684e7c9b54426735d51dcd7e307ad

**Comment by mtkopone** [comment]
Merged with #6
